// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtjD55Yy84mo4a2ZPhua1IJgBReYo7Nn8',
    appId: '1:278087162125:web:8fd1de64c5d06f0e233844',
    messagingSenderId: '278087162125',
    projectId: 'restaurantorder-39662',
    authDomain: 'restaurantorder-39662.firebaseapp.com',
    storageBucket: 'restaurantorder-39662.appspot.com',
    measurementId: 'G-XNGCZQLX4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUkUnfyuFO5A3JUN8FWYSGjxQRDHhwzk0',
    appId: '1:278087162125:android:c9fb5dec1baad7d2233844',
    messagingSenderId: '278087162125',
    projectId: 'restaurantorder-39662',
    storageBucket: 'restaurantorder-39662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF4JTp-mGThRds-w97-8LhsJ0W4o4jui0',
    appId: '1:278087162125:ios:d8e2b7c38b3a867a233844',
    messagingSenderId: '278087162125',
    projectId: 'restaurantorder-39662',
    storageBucket: 'restaurantorder-39662.appspot.com',
    iosBundleId: 'com.example.mobileOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF4JTp-mGThRds-w97-8LhsJ0W4o4jui0',
    appId: '1:278087162125:ios:d8e2b7c38b3a867a233844',
    messagingSenderId: '278087162125',
    projectId: 'restaurantorder-39662',
    storageBucket: 'restaurantorder-39662.appspot.com',
    iosBundleId: 'com.example.mobileOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtjD55Yy84mo4a2ZPhua1IJgBReYo7Nn8',
    appId: '1:278087162125:web:55734c17e24f769d233844',
    messagingSenderId: '278087162125',
    projectId: 'restaurantorder-39662',
    authDomain: 'restaurantorder-39662.firebaseapp.com',
    storageBucket: 'restaurantorder-39662.appspot.com',
    measurementId: 'G-HCJ3B54V11',
  );
}
